version: '3'

services:
  shell:
    container_name: vice-python
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: vice
      POSTGRES_USER: vice
      POSTGRES_PASSWORD: vice
    volumes:
      - ./.docker/postgres/data/:/var/lib/postgresql/data
      - ./.docker/postgres/initdb.d/:/docker-entrypoint-initdb.d/
    ports:
    - 5432:5432